### ISSUE TITLE
Migration entry point for account balance(claimed).

### ISSUE THREAD

**Issue by hackfisher** [dacplayproject/cpp-play2-ui#3]

**Comment by AlexChien** [comment]
api related `signed_transaction wallet_api::migrate_account_balance( string name, string eth_address, bool broadcast )`

- list accounts with PLS balance
- select accounts to migrate
- provide ETH address
- migrate will generate op per account to be migrated

Simplify UI
- remove functions as transfer, create asset and many others
- keep balance claim feature

**Comment by AlexChien** [comment]
closed by e46cfba..27ea686
